### ISSUE TITLE
How to stop the job?

### ISSUE THREAD

**Issue by Berezhnyk** [robdmc/crontabs#7] opened 2020-04-13 13:20 UTC
![image](https://user-images.githubusercontent.com/6099167/79123190-42604200-7da2-11ea-9f35-d31164755ef9.png)

Used example in PyCharm 2020.1 on Windows 10

```
def my_job(*args, **kwargs):
    print('args={} kwargs={} running at {}'.format(args, kwargs, datetime.datetime.now()))
```

```
Cron().schedule(
        Tab(name='run_my_job').every(seconds=5).run(my_job, 'my_arg', my_kwarg='hello')
    ).go()
```
After trying stopping a console it looks like the job is still running but just without calling `my_job`

**Comment by robdmc** [comment] 2020-05-01 18:10
Did you ever figure out what's happening here?  I only intended to support linux-based systems with crontabs, but if you've gotten it to work with windows, I'm interested.  I cannot reproduce your issues on my mac.

**Comment by robdmc** [comment] 2020-06-05 23:00
Closing this for now.  Hit me up again if you still have questions.

**Closed as completed by robdmc** 2020-06-05 23:00 UTC

**Comment by Neil2893** [comment] 2021-07-02 11:40
![image](https://user-images.githubusercontent.com/16524261/124267408-ca2e9980-db6a-11eb-8f2e-9286cb785ae2.png)
With jupyterlab on manjaro(an arch-based linux distro), I interrupted the kernel at 2021-07-02T19:21:24.800226, and things went as Berezhnyk described.
![image](https://user-images.githubusercontent.com/16524261/124268207-cea78200-db6b-11eb-898a-674519d09c94.png)
But everything works fine under a terminal, so it doesn't hurt much if not fixed.
